/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.*;
import javax.swing.*;
import model.connection.ConnectionFactory;
import model.dao.UsuarioDAO;
import model.vo.Usuario;
import net.proteanit.sql.DbUtils;


public class TelaUsuario extends javax.swing.JInternalFrame {

    public JButton getjBotaoAdd() {
        return jBotaoAdd;
    }

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
    }

    private void limpaCampos() {
        jTxtNome.setText(null);
        jTxtUsuario.setText(null);
        jTxtSenha.setText(null);
    }

    private void pesquisar_cliente() {

        String sql = "SELECT * FROM tbusuarios WHERE login LIKE ?";
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {

            stmt = con.prepareStatement(sql);
            stmt.setString(1, jTxtUsuPesquisa.getText() + "%");
            rs = stmt.executeQuery();

            jTbUsuario.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println("Erro: " + e);
        }
    }

    public void setar_campos() {
        int setar = jTbUsuario.getSelectedRow();

        jTxtNome.setText(jTbUsuario.getModel().getValueAt(setar, 1).toString());
        jTxtUsuario.setText(jTbUsuario.getModel().getValueAt(setar, 2).toString());
        jTxtSenha.setText(jTbUsuario.getModel().getValueAt(setar, 3).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtSenha = new javax.swing.JPasswordField();
        jBotaoAdd = new javax.swing.JButton();
        jBotaoAtualizar = new javax.swing.JButton();
        jBotaoDeletar = new javax.swing.JButton();
        jTxtUsuPesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Usuario");
        setToolTipText("Tela Usuario");

        jTbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Usuario", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbUsuarioMouseClicked(evt);
            }
        });
        jTbUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbUsuarioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTbUsuario);
        if (jTbUsuario.getColumnModel().getColumnCount() > 0) {
            jTbUsuario.getColumnModel().getColumn(0).setResizable(false);
            jTbUsuario.getColumnModel().getColumn(1).setResizable(false);
            jTbUsuario.getColumnModel().getColumn(2).setResizable(false);
            jTbUsuario.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("Nome:");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Senha:");

        jBotaoAdd.setText("Adicionar");
        jBotaoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoAddActionPerformed(evt);
            }
        });

        jBotaoAtualizar.setText("Atualizar");
        jBotaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoAtualizarActionPerformed(evt);
            }
        });

        jBotaoDeletar.setText("Deletar");
        jBotaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoDeletarActionPerformed(evt);
            }
        });

        jTxtUsuPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtUsuPesquisaKeyReleased(evt);
            }
        });

        jButton1.setText("botao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtUsuPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jBotaoAdd)
                            .addGap(76, 76, 76)
                            .addComponent(jBotaoAtualizar)
                            .addGap(76, 76, 76)
                            .addComponent(jBotaoDeletar)
                            .addGap(138, 138, 138))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtSenha)
                    .addComponent(jTxtUsuario)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtUsuPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoAdd)
                    .addComponent(jBotaoAtualizar)
                    .addComponent(jBotaoDeletar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoDeletarActionPerformed

        Usuario u = new Usuario();
        UsuarioDAO udao = new UsuarioDAO();

        if (jTbUsuario.getSelectedRow() != -1) {

            u.setId((int) jTbUsuario.getValueAt(jTbUsuario.getSelectedRow(), 0));

            udao.delete(u);

            limpaCampos();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um usuario para excluir");
        }
    }//GEN-LAST:event_jBotaoDeletarActionPerformed

    private void jBotaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoAtualizarActionPerformed

        Usuario u = new Usuario();
        UsuarioDAO dao = new UsuarioDAO();

        u.setNome(jTxtNome.getText());
        u.setLogin(jTxtUsuario.getText());
        u.setSenha(String.valueOf(jTxtSenha.getPassword()));
        u.setId((int) jTbUsuario.getValueAt(jTbUsuario.getSelectedRow(), 0));

        dao.update(u);

        limpaCampos();

    }//GEN-LAST:event_jBotaoAtualizarActionPerformed

    private void jBotaoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoAddActionPerformed
        Usuario u = new Usuario();
        UsuarioDAO dao = new UsuarioDAO();

        u.setNome(jTxtNome.getText());
        u.setLogin(jTxtUsuario.getText());
        u.setSenha(String.valueOf(jTxtSenha.getPassword()));

        dao.create(u);

        limpaCampos();

    }//GEN-LAST:event_jBotaoAddActionPerformed

    private void jTbUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbUsuarioKeyReleased
    }//GEN-LAST:event_jTbUsuarioKeyReleased

    private void jTbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbUsuarioMouseClicked
        setar_campos();
    }//GEN-LAST:event_jTbUsuarioMouseClicked

    private void jTxtUsuPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUsuPesquisaKeyReleased
        pesquisar_cliente();
    }//GEN-LAST:event_jTxtUsuPesquisaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotaoAdd;
    private javax.swing.JButton jBotaoAtualizar;
    private javax.swing.JButton jBotaoDeletar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbUsuario;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JPasswordField jTxtSenha;
    private javax.swing.JTextField jTxtUsuPesquisa;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
