/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.dao.UsuarioDAO;
import model.vo.Usuario;

/**
 *
 * @author DHEYSON
 */
public class TelaUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaUsuario() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTbUsuario.getModel();
        jTbUsuario.setRowSorter(new TableRowSorter(modelo));
        
        readTelaUsuario();
    }

    public void readTelaUsuario() {
        DefaultTableModel modelo = (DefaultTableModel) jTbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDAO usuariodao = new UsuarioDAO();

        for (Usuario u : usuariodao.read()) {

            modelo.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getLogin(),
                u.getSenha()
            });
        }
    }
    
    private void limpaCampos() {
        jTxtNome.setText(null);
        jTxtUsuario.setText(null);
        jTxtSenha.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtSenha = new javax.swing.JPasswordField();
        jBotaoAdd = new javax.swing.JButton();
        jBotaoAtualizar = new javax.swing.JButton();
        jBotaoDeletar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jTbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Usuario", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbUsuarioMouseClicked(evt);
            }
        });
        jTbUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTbUsuarioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTbUsuario);
        if (jTbUsuario.getColumnModel().getColumnCount() > 0) {
            jTbUsuario.getColumnModel().getColumn(0).setResizable(false);
            jTbUsuario.getColumnModel().getColumn(1).setResizable(false);
            jTbUsuario.getColumnModel().getColumn(2).setResizable(false);
            jTbUsuario.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setText("Nome:");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Senha:");

        jBotaoAdd.setText("Adicionar");
        jBotaoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoAddActionPerformed(evt);
            }
        });

        jBotaoAtualizar.setText("Atualizar");
        jBotaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoAtualizarActionPerformed(evt);
            }
        });

        jBotaoDeletar.setText("Deletar");
        jBotaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtSenha)
                    .addComponent(jTxtUsuario)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBotaoAdd)
                        .addGap(76, 76, 76)
                        .addComponent(jBotaoAtualizar)
                        .addGap(76, 76, 76)
                        .addComponent(jBotaoDeletar)
                        .addGap(138, 138, 138))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoAdd)
                    .addComponent(jBotaoAtualizar)
                    .addComponent(jBotaoDeletar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoDeletarActionPerformed

        Usuario u = new Usuario();
        UsuarioDAO udao = new UsuarioDAO();

        if (jTbUsuario.getSelectedRow() != -1) {

            u.setId((int) jTbUsuario.getValueAt(jTbUsuario.getSelectedRow(), 0));

            udao.delete(u);

            limpaCampos();

            readTelaUsuario();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um usuario para excluir");
        }
    }//GEN-LAST:event_jBotaoDeletarActionPerformed

    private void jBotaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoAtualizarActionPerformed

        Usuario u = new Usuario();
        UsuarioDAO dao = new UsuarioDAO();

        u.setNome(jTxtNome.getText());
        u.setLogin(jTxtUsuario.getText());
        u.setSenha(String.valueOf(jTxtSenha.getPassword()));
        u.setId((int) jTbUsuario.getValueAt(jTbUsuario.getSelectedRow(), 0));

        dao.update(u);

        limpaCampos();

        readTelaUsuario();
    }//GEN-LAST:event_jBotaoAtualizarActionPerformed

    private void jBotaoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoAddActionPerformed
        Usuario u = new Usuario();
        UsuarioDAO dao = new UsuarioDAO();

        u.setNome(jTxtNome.getText());
        u.setLogin(jTxtUsuario.getText());
        u.setSenha(String.valueOf(jTxtSenha.getPassword()));

        dao.create(u);

        limpaCampos();

        readTelaUsuario();
    }//GEN-LAST:event_jBotaoAddActionPerformed

    private void jTbUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbUsuarioKeyReleased

        if (jTbUsuario.getSelectedRow() != -1) {

            jTxtNome.setText(jTbUsuario.getValueAt(jTbUsuario.getSelectedRow(), 1).toString());
            jTxtUsuario.setText(jTbUsuario.getValueAt(jTbUsuario.getSelectedRow(), 2).toString());
            jTxtSenha.setText(jTbUsuario.getValueAt(jTbUsuario.getSelectedRow(), 3).toString());
        }

    }//GEN-LAST:event_jTbUsuarioKeyReleased

    private void jTbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbUsuarioMouseClicked
        if (jTbUsuario.getSelectedRow() != -1) {

            jTxtNome.setText(jTbUsuario.getValueAt(jTbUsuario.getSelectedRow(), 1).toString());
            jTxtUsuario.setText(jTbUsuario.getValueAt(jTbUsuario.getSelectedRow(), 2).toString());
            jTxtSenha.setText(jTbUsuario.getValueAt(jTbUsuario.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_jTbUsuarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotaoAdd;
    private javax.swing.JButton jBotaoAtualizar;
    private javax.swing.JButton jBotaoDeletar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbUsuario;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JPasswordField jTxtSenha;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
